gamepad: Xbox360
inputs:
  axes:
    # LEFT-X:
    #   mapping: yaw
    #   mode: normal
    #   weight: 100
    #   min: -100
    #   max: 100
    #   center: 0
    #   deadband: 7
    #   neutral: 0
    # LEFT-Y:
    #   mapping: heave
    #   mode: normal
    #   weight: 100
    #   min: 100
    #   max: -100
    #   center: 0
    #   deadband: 7
    #   neutral: 0
    # RIGHT-X:
    #   mapping: sway
    #   mode: normal
    #   weight: 100
    #   min: -100
    #   max: 100
    #   center: 0
    #   deadband: 7
    #   neutral: 0
    # RIGHT-Y:
    #   mapping: surge
    #   mode: normal
    #   weight: 100
    #   min: 100
    #   max: -100
    #   center: 0
    #   deadband: 7
    #   neutral: 0
    # LT:
    #   mapping: pitch.left
    #   mode: normal
    #   weight: 50
    #   min: 100
    #   max: -100
    #   center: 0
    #   deadband: 0
    #   neutral: -1.0
    # RT:
    #   mapping: pitch.right
    #   mode: normal
    #   weight: 50
    #   min: -100
    #   max: 100
    #   center: 0
    #   deadband: 0
    #   neutral: -1.0
    6: # D-PAD Left-Right
      mapping: camera_pan
      mode: normal
      weight: 100
      min: -100
      max: 100
      center: 0
      deadband: 0
      neutral: 0
    7: # D-PAD Up-Down
      mapping: camera_tilt
      mode: normal
      weight: 100
      min: 100
      max: -100
      center: 0
      deadband: 0
      neutral: 0
    LT:
      mapping: attatchment_servo.left
      mode: normal
      weight: 50
      min: 100
      max: -100
      center: 0
      deadband: 0
      neutral: -1.0
    RT:
      mapping: attatchment_servo.right
      mode: normal
      weight: 50
      min: -100
      max: 100
      center: 0
      deadband: 0
      neutral: -1.0
  buttons:
    # A:
    #   mode: normal
    #   pressed: 100
    #   released: -100

    #   mapping: heave
    # B:
    #   mode: normal
    #   pressed: 100
    #   released: -100

    #   mapping:
    # X:
    #   mode: normal
    #   pressed: 100
    #   released: -100

    #   mapping:
    Y:
      mapping: panorama
      mode: normal
      pressed: 100
      released: -100
    LA:
      mapping: camera_pan.reset
      mode: normal
      pressed: 100
      released: -100
    RA:
      mapping: camera_tilt.reset
      mode: normal
      pressed: 100
      released: -100
    LB:
      mapping: roll.left
      mode: normal
      pressed: -100
      released: 0
    RB:
      mapping: roll.right
      mode: normal
      pressed: 100
      released: 0
    # BACK:
    #   mode: normal
    #   pressed: 100
    #   released: -100

    #   mapping: panorama
    # START:
    #   mode: normal
    #   pressed: 100
    #   released: -100

    #   mapping:
mappings:
  roll:
    type: add
    output: udp.rc2
    min: -100
    max: 100
  pitch:
    type: add
    output: udp.rc1
    min: -100
    max: 100
  yaw:
    type: passthrough
    output: udp.rc4
    min: -100
    max: 100
  heave: # Up and Down
    type: passthrough
    output: udp.rc3
    min: -100
    max: 100
  surge: # Forwards and Backwards
    type: passthrough
    output: udp.rc5
    min: -100
    max: 100
  sway: # Side to Side
    type: passthrough
    output: udp.rc6
    min: -100
    max: 100
  camera_pan:
    type: relative
    output: udp.rc12
    min: -100
    max: 100
    center: 0
    speed: 5
  camera_tilt:
    type: relative
    output: udp.rc13
    min: -100
    max: 100
    center: 0
    speed: 5
  attatchment_servo:
    type: add
    output: udp.rc14
    min: -100
    max: 100
    center: 0

special_functions:
  panorama:
    function: image_stitch
    mappings:
      pan:
        mapping: camera_pan
        min: -100
        max: 100
        step: 16
    output_dir: "panorama" # TODO: create a list of available variables for substitution
    port: 5602

outputs:
  udp:
    type: selk_udp
    target:
      host: 192.168.137.20
      port: 5005
