gamepad: Xbox360
inputs:
  axes:
    LEFT-X:
      mode: normal
      weight: 100
      min: -100
      max: 100
      center: 0
      deadband: 7
      neutral: 0

      mapping: yaw
    LEFT-Y:
      mode: normal
      weight: 100
      min: 100
      max: -100
      center: 0
      deadband: 7
      neutral: 0

      mapping: heave
    RIGHT-X:
      mode: normal
      weight: 100
      min: -100
      max: 100
      center: 0
      deadband: 7
      neutral: 0

      mapping: sway
    RIGHT-Y:
      mode: normal
      weight: 100
      min: 100
      max: -100
      center: 0
      deadband: 7
      neutral: 0

      mapping: surge
    6: # D-PAD Left-Right
      mode: normal
      weight: 100
      min: -100
      max: 100
      center: 0
      deadband: 0
      neutral: 0

      mapping: camera_pan
    7: # D-PAD Up-Down
      mode: normal
      weight: 100
      min: 100
      max: -100
      center: 0
      deadband: 0
      neutral: 0

      mapping: camera_tilt
    LT:
      mode: normal
      weight: 50
      min: 100
      max: -100
      center: 0
      deadband: 0
      neutral: -1.0

      mapping: pitch.left
    RT:
      mode: normal
      weight: 50
      min: -100
      max: 100
      center: 0
      deadband: 0
      neutral: -1.0

      mapping: pitch.right
  buttons:
    A:
      mode: normal
      pressed: 100
      released: -100

      mapping: attatchment_servo
    # B:
    #   mode: normal
    #   pressed: 100
    #   released: -100

    #   mapping:
    # X:
    #   mode: normal
    #   pressed: 100
    #   released: -100

    #   mapping:
    # Y:
    #   mode: normal
    #   pressed: 100
    #   released: -100

    #   mapping:
    LA:
      mode: normal
      pressed: 100
      released: -100

      mapping: camera_pan.reset
    RA:
      mode: normal
      pressed: 100
      released: -100

      mapping: camera_tilt.reset
    LB:
      mode: normal
      pressed: -10
      released: 0

      mapping: roll.left
    RB:
      mode: normal
      pressed: 10
      released: 0

      mapping: roll.right
    # BACK:
    #   mode: normal
    #   pressed: 100
    #   released: -100

    #   mapping:
    # START:
    #   mode: normal
    #   pressed: 100
    #   released: -100

    #   mapping:
mappings:
  roll:
    type: add
    output: udp.rc1
    min: -100
    max: 100
  pitch:
    type: add
    output: udp.rc2
    min: -100
    max: 100
  yaw:
    type: passthrough
    output: udp.rc4
    min: -100
    max: 100
  heave: # Up and Down
    type: passthrough
    output: udp.rc3
    min: -100
    max: 100
  surge: # Forwards and Backwards
    type: passthrough
    output: udp.rc5
    min: -100
    max: 100
  sway: # Side to Side
    type: passthrough
    output: udp.rc6
    min: -100
    max: 100
  camera_pan:
    type: relative
    output: udp.rc7
    min: -100
    max: 100
    center: 0
    speed: 5
  camera_tilt:
    type: relative
    output: udp.rc8
    min: -100
    max: 100
    center: 0
    speed: 5
  attatchment_servo:
    type: toggle_latch
    output: udp.rc9
    min: -100
    max: 100

special_functions:
  panorama:
    function: image_stitch
    mappings:
      pan:
        mapping: camera_pan
        min: -100
        max: 100
        step: 10
      tilt: null
    images_dir: "{current_time}_panorama" # TODO: create a list of available variables for substitution

outputs:
  udp:
    type: selk_udp
    target:
      host: 192.168.137.20
      port: 5005
