# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rc_channels.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11rc_channels.proto\x12\x0crc_interface\"\xe3\x01\n\nRCChannels\x12\x0b\n\x03rc1\x18\x01 \x01(\r\x12\x0b\n\x03rc2\x18\x02 \x01(\r\x12\x0b\n\x03rc3\x18\x03 \x01(\r\x12\x0b\n\x03rc4\x18\x04 \x01(\r\x12\x0b\n\x03rc5\x18\x05 \x01(\r\x12\x0b\n\x03rc6\x18\x06 \x01(\r\x12\x0b\n\x03rc7\x18\x07 \x01(\r\x12\x0b\n\x03rc8\x18\x08 \x01(\r\x12\x0b\n\x03rc9\x18\t \x01(\r\x12\x0c\n\x04rc10\x18\n \x01(\r\x12\x0c\n\x04rc11\x18\x0b \x01(\r\x12\x0c\n\x04rc12\x18\x0c \x01(\r\x12\x0c\n\x04rc13\x18\r \x01(\r\x12\x0c\n\x04rc14\x18\x0e \x01(\r\x12\x0c\n\x04rc15\x18\x0f \x01(\r\x12\x0c\n\x04rc16\x18\x10 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rc_channels_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RCCHANNELS._serialized_start=36
  _RCCHANNELS._serialized_end=263
# @@protoc_insertion_point(module_scope)
